### ISSUE TITLE
Fails to build on Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by anorm** [cnangel/python-libconfig#10]
I'm unable to build python-libconfig on 64bit Ubuntu 12.04 LTS using libconfig++ version 1.3.2.

```
$ python setup.py build
running build
running build_ext
building 'pylibconfig' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/opt/local/include -I/usr/include/python2.7 -c src/pylibconfig.cc -o build/temp.linux-x86_64-2.7/src/pylibconfig.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
src/pylibconfig.cc: In member function ‘void pyConfig::readString(const char*)’:
src/pylibconfig.cc:34:17: error: ‘class libconfig::Config’ has no member named ‘readString’
error: command 'gcc' failed with exit status 1
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise
```

```
$ uname -a
Linux pkt-testbox 3.8.0-42-generic #63~precise1-Ubuntu SMP Fri Jul 4 21:16:26 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ dpkg --get-selections | grep libconfig
libconfig++8                    install
libconfig++8-dev                install
libconfig8                  install
libconfig8-dev                  install
```

```
$ apt-cache show libconfig++8-dev | grep Version
Version: 1.3.2-2ubuntu2
```
